"""empty message

Revision ID: 12653db42934
Revises: 562084d73d51
Create Date: 2014-12-13 14:52:49.170575

"""

# revision identifiers, used by Alembic.
revision = '12653db42934'
down_revision = '562084d73d51'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tutor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('school', sa.String(length=64), nullable=True),
    sa.Column('grade', sa.String(length=64), nullable=True),
    sa.Column('major', sa.String(length=64), nullable=True),
    sa.Column('gpa', sa.Float(), nullable=True),
    sa.Column('phone', sa.String(length=10), nullable=True),
    sa.Column('relExp', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(u'ix_tutor_email', 'tutor', ['email'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_tutor_email', table_name='tutor')
    op.drop_table('tutor')
    ### end Alembic commands ###
