"""empty message

Revision ID: 1381f58ef419
Revises: 41cf6932ab30
Create Date: 2015-01-05 22:30:09.516611

"""

# revision identifiers, used by Alembic.
revision = '1381f58ef419'
down_revision = '41cf6932ab30'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=64), nullable=True))
    op.create_index(u'ix_users_username', 'users', ['username'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_users_username', table_name='users')
    op.drop_column('users', 'username')
    ### end Alembic commands ###
