"""empty message

Revision ID: 14ad14679205
Revises: 3995e6f6fdf0
Create Date: 2015-05-06 19:14:52.959530

"""

# revision identifiers, used by Alembic.
revision = '14ad14679205'
down_revision = '3995e6f6fdf0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column(u'get_help', 'start_datetime')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'get_help', sa.Column('start_datetime', sa.DATETIME(), nullable=True))
    op.drop_table('schedule')
    ### end Alembic commands ###
