"""empty message

Revision ID: 235187658730
Revises: None
Create Date: 2014-12-13 23:55:33.195849

"""

# revision identifiers, used by Alembic.
revision = '235187658730'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tutor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('school', sa.String(length=64), nullable=True),
    sa.Column('grade', sa.String(length=64), nullable=True),
    sa.Column('major', sa.String(length=64), nullable=True),
    sa.Column('gpa', sa.Float(), nullable=True),
    sa.Column('phonenumber', sa.String(length=10), nullable=True),
    sa.Column('relexp', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(u'ix_tutor_email', 'tutor', ['email'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(u'ix_users_email', 'users', ['email'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index(u'ix_tutor_email', table_name='tutor')
    op.drop_table('tutor')
    ### end Alembic commands ###
