"""empty message

Revision ID: 251f3cafad7d
Revises: 1381f58ef419
Create Date: 2015-04-08 21:33:57.692528

"""

# revision identifiers, used by Alembic.
revision = '251f3cafad7d'
down_revision = '1381f58ef419'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(length=64), nullable=True),
    sa.Column('school', sa.String(length=64), nullable=True),
    sa.Column('grade', sa.String(length=64), nullable=True),
    sa.Column('major', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('get_help',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('class_name', sa.String(length=64), nullable=True),
    sa.Column('class_number', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('help_comment', sa.String(length=64), nullable=True),
    sa.Column('duration', sa.String(length=64), nullable=True),
    sa.Column('start_datetime', sa.DateTime(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(u'ix_get_help_class_number', 'get_help', ['class_number'], unique=True)
    op.drop_column(u'tutor', u'email')
    op.add_column(u'users', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column(u'users', sa.Column('updated_on', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'users', 'updated_on')
    op.drop_column(u'users', 'created_on')
    op.add_column(u'tutor', sa.Column(u'email', sa.VARCHAR(length=64), nullable=True))
    op.drop_index(u'ix_get_help_class_number', table_name='get_help')
    op.drop_table('get_help')
    op.drop_table('student')
    ### end Alembic commands ###
