"""empty message

Revision ID: 3995e6f6fdf0
Revises: 251f3cafad7d
Create Date: 2015-04-18 12:38:25.946834

"""

# revision identifiers, used by Alembic.
revision = '3995e6f6fdf0'
down_revision = '251f3cafad7d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signup_email'), 'signup', ['email'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signup_email'), table_name='signup')
    op.drop_table('signup')
    ### end Alembic commands ###
