"""empty message

Revision ID: 41cf6932ab30
Revises: 235187658730
Create Date: 2014-12-20 22:01:07.154677

"""

# revision identifiers, used by Alembic.
revision = '41cf6932ab30'
down_revision = '235187658730'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tutor', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('tutor', sa.Column('updated_on', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tutor', 'updated_on')
    op.drop_column('tutor', 'created_on')
    ### end Alembic commands ###
