"""empty message

Revision ID: 45e69d6f3d5
Revises: 12653db42934
Create Date: 2014-12-13 15:38:50.302100

"""

# revision identifiers, used by Alembic.
revision = '45e69d6f3d5'
down_revision = '12653db42934'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tutor', sa.Column('fullname', sa.String(length=64), nullable=True))
    op.add_column('tutor', sa.Column('phonenumber', sa.String(length=10), nullable=True))
    op.drop_column('tutor', u'phone')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tutor', sa.Column(u'phone', sa.VARCHAR(length=10), nullable=True))
    op.drop_column('tutor', 'phonenumber')
    op.drop_column('tutor', 'fullname')
    ### end Alembic commands ###
